package StoreApp;


/**
* StoreApp/StorePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from store.idl
* Wednesday, October 21, 2020 7:47:43 PM EDT
*/

public abstract class StorePOA extends org.omg.PortableServer.Servant
 implements StoreApp.StoreOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("addItem", new java.lang.Integer (0));
    _methods.put ("removeItem", new java.lang.Integer (1));
    _methods.put ("listItemAvailability", new java.lang.Integer (2));
    _methods.put ("purchaseItem", new java.lang.Integer (3));
    _methods.put ("findItem", new java.lang.Integer (4));
    _methods.put ("returnItem", new java.lang.Integer (5));
    _methods.put ("exchange", new java.lang.Integer (6));
    _methods.put ("requestUpdateOfCustomerBudgetLog", new java.lang.Integer (7));
    _methods.put ("waitList", new java.lang.Integer (8));
    _methods.put ("shutdown", new java.lang.Integer (9));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  //Manager Invokable methods
       case 0:  // StoreApp/Store/addItem
       {
         String managerID = in.read_string ();
         String itemID = in.read_string ();
         String itemName = in.read_string ();
         int quantity = in.read_long ();
         double price = in.read_double ();
         String $result = null;
         $result = this.addItem (managerID, itemID, itemName, quantity, price);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // StoreApp/Store/removeItem
       {
         String managerID = in.read_string ();
         String itemID = in.read_string ();
         int quantity = in.read_long ();
         String $result = null;
         $result = this.removeItem (managerID, itemID, quantity);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // StoreApp/Store/listItemAvailability
       {
         String managerID = in.read_string ();
         String $result = null;
         $result = this.listItemAvailability (managerID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }


  //Client Invokable methods
       case 3:  // StoreApp/Store/purchaseItem
       {
         String customerID = in.read_string ();
         String itemID = in.read_string ();
         String dateOfPurchase = in.read_string ();
         boolean $result = false;
         $result = this.purchaseItem (customerID, itemID, dateOfPurchase);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 4:  // StoreApp/Store/findItem
       {
         String customerID = in.read_string ();
         String itemName = in.read_string ();
         String $result = null;
         $result = this.findItem (customerID, itemName);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // StoreApp/Store/returnItem
       {
         String customerID = in.read_string ();
         String itemID = in.read_string ();
         String dateOfReturn = in.read_string ();
         String $result = null;
         $result = this.returnItem (customerID, itemID, dateOfReturn);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 6:  // StoreApp/Store/exchange
       {
         String customerID = in.read_string ();
         String newItemID = in.read_string ();
         String oldItemID = in.read_string ();
         String $result = null;
         $result = this.exchange (customerID, newItemID, oldItemID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }


  //Not to be used remotely
       case 7:  // StoreApp/Store/requestUpdateOfCustomerBudgetLog
       {
         String customerID = in.read_string ();
         double price = in.read_double ();
         this.requestUpdateOfCustomerBudgetLog (customerID, price);
         out = $rh.createReply();
         break;
       }


  //WaitList method
       case 8:  // StoreApp/Store/waitList
       {
         String customerID = in.read_string ();
         String itemID = in.read_string ();
         String dateOfPurchase = in.read_string ();
         boolean $result = false;
         $result = this.waitList (customerID, itemID, dateOfPurchase);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 9:  // StoreApp/Store/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:StoreApp/Store:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Store _this() 
  {
    return StoreHelper.narrow(
    super._this_object());
  }

  public Store _this(org.omg.CORBA.ORB orb) 
  {
    return StoreHelper.narrow(
    super._this_object(orb));
  }


} // class StorePOA
