package StoreApp;


/**
* StoreApp/Store.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from store.idl
* Wednesday, October 21, 2020 12:21:33 AM EDT
*/

public interface Store extends StoreOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Store
