package StoreApp;


/**
* StoreApp/StoreOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from store.idl
* Thursday, October 22, 2020 10:16:51 PM EDT
*/

public interface StoreOperations 
{

  //Manager Invokable methods
  String addItem (String managerID, String itemID, String itemName, int quantity, double price);
  String removeItem (String managerID, String itemID, int quantity);
  String listItemAvailability (String managerID);

  //Client Invokable methods
  String purchaseItem (String customerID, String itemID, String dateOfPurchase);
  String findItem (String customerID, String itemName);
  String returnItem (String customerID, String itemID, String dateOfReturn);
  String exchange (String customerID, String newItemID, String oldItemID);

  //Not to be used remotely
  void requestUpdateOfCustomerBudgetLog (String customerID, double price);

  //WaitList method
  boolean waitList (String customerID, String itemID, String dateOfPurchase);
  void shutdown ();
} // interface StoreOperations
