package StoreApp;


/**
* StoreApp/StoreOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from store.idl
* Wednesday, October 21, 2020 12:21:33 AM EDT
*/

public interface StoreOperations 
{

  //Manager Invokable methods
  String addItem (String managerID, String itemID, String itemName, int quantity, double price);
  String removeItem (String managerID, String itemID, int quantity);
  String listItemAvailability (String managerID);

  //Client Invokable methods
  boolean purchaseItem (String customerID, String itemID, String dateOfPurchase);
  String findItem (String customerID, String itemName);
  String returnItem (String customerID, String itemID, String dateOfReturn);

  //Not to be used remotely
  void requestUpdateOfCustomerBudgetLog (String customerID, double price);

  //WaitList method
  boolean waitList (String customerID, String itemID, String dateOfPurchase);
  void shutdown ();
} // interface StoreOperations
